[package]
name = "rust_project_reader"
version = "0.1.0"
authors = ["Robertas <robertasj8@gmail.com>"]
edition = "2021"
rust-version = "1.68.0"

[dependencies]
clipboard = "0.5.0"
colored = "2.0.0"
walkdir = "2.3.3"
